# Form implementation generated from reading ui file 'src/ui/admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from main import ICONS_DIR


class Ui_admin_dashboard(object):
    def setupUi(self, admin_dashboard):
        admin_dashboard.setObjectName("admin_dashboard")
        admin_dashboard.resize(782, 603)
        admin_dashboard.setMinimumSize(QtCore.QSize(782, 603))
        admin_dashboard.setMaximumSize(QtCore.QSize(782, 603))
        admin_dashboard.setStyleSheet("#admin_dashboard{\n"
"    background-color: #8EA09F;\n"
"}")
        self.admin_widget = QtWidgets.QWidget(parent=admin_dashboard)
        self.admin_widget.setGeometry(QtCore.QRect(0, 0, 781, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_widget.sizePolicy().hasHeightForWidth())
        self.admin_widget.setSizePolicy(sizePolicy)
        self.admin_widget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none;\n"
"}\n"
"\n"
"#appHeader{\n"
"    color: #293737;\n"
"}\n"
"\n"
"#card1, #card2, #card3, #card4{\n"
"background-color: #fefeff;\n"
"border-radius: 20px;\n"
"}")
        self.admin_widget.setObjectName("admin_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.admin_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.admin_left_menu = QtWidgets.QWidget(parent=self.admin_widget)
        self.admin_left_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.admin_left_menu.setStyleSheet("#admin_left_menu{\n"
"    background-color: #293737;\n"
"}")
        self.admin_left_menu.setObjectName("admin_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.admin_left_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.admin_side_menu = QtWidgets.QFrame(parent=self.admin_left_menu)
        self.admin_side_menu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.admin_side_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_side_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_side_menu.setObjectName("admin_side_menu")
        self.layoutWidget = QtWidgets.QWidget(parent=self.admin_side_menu)
        self.layoutWidget.setGeometry(QtCore.QRect(-10, -10, 201, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.admin_vertical_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.admin_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.admin_vertical_layout.setObjectName("admin_vertical_layout")
        self.admin_frame_4 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.admin_frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.admin_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame_4.setObjectName("admin_frame_4")
        self.admin_lable = QtWidgets.QLabel(parent=self.admin_frame_4)
        self.admin_lable.setGeometry(QtCore.QRect(40, 20, 125, 24))
        self.admin_lable.setMaximumSize(QtCore.QSize(125, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.admin_lable.setFont(font)
        self.admin_lable.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.admin_lable.setObjectName("admin_lable")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.admin_frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 60, 201, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.admin_vertical_layout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.admin_vertical_layout_2.setContentsMargins(0, 0, 0, 0)
        self.admin_vertical_layout_2.setSpacing(10)
        self.admin_vertical_layout_2.setObjectName("admin_vertical_layout_2")
        self.admin_home_bn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_home_bn.sizePolicy().hasHeightForWidth())
        self.admin_home_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.admin_home_bn.setFont(font)
        self.admin_home_bn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.admin_home_bn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "home.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.admin_home_bn.setIcon(icon)
        self.admin_home_bn.setIconSize(QtCore.QSize(32, 32))
        self.admin_home_bn.setObjectName("admin_home_bn")
        self.admin_vertical_layout_2.addWidget(self.admin_home_bn)
        self.assign_drivers_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assign_drivers_btn.sizePolicy().hasHeightForWidth())
        self.assign_drivers_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.assign_drivers_btn.setFont(font)
        self.assign_drivers_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assign_drivers_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "assign_driver_img.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.assign_drivers_btn.setIcon(icon1)
        self.assign_drivers_btn.setIconSize(QtCore.QSize(35, 35))
        self.assign_drivers_btn.setObjectName("assign_drivers_btn")
        self.admin_vertical_layout_2.addWidget(self.assign_drivers_btn)
        self.view_users_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_users_btn.sizePolicy().hasHeightForWidth())
        self.view_users_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.view_users_btn.setFont(font)
        self.view_users_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.view_users_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "view_users_img.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.view_users_btn.setIcon(icon2)
        self.view_users_btn.setIconSize(QtCore.QSize(35, 35))
        self.view_users_btn.setObjectName("view_users_btn")
        self.admin_vertical_layout_2.addWidget(self.view_users_btn)
        self.admin_frame_5 = QtWidgets.QFrame(parent=self.admin_frame_4)
        self.admin_frame_5.setGeometry(QtCore.QRect(20, 490, 161, 81))
        self.admin_frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame_5.setObjectName("admin_frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.admin_frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.admin_logout_btn = QtWidgets.QPushButton(parent=self.admin_frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.admin_logout_btn.setFont(font)
        self.admin_logout_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.admin_logout_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A;\n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #d17575;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.admin_logout_btn.setObjectName("admin_logout_btn")
        self.verticalLayout_12.addWidget(self.admin_logout_btn)
        self.admin_vertical_layout.addWidget(self.admin_frame_4)
        self.verticalLayout_2.addWidget(self.admin_side_menu)
        self.horizontalLayout.addWidget(self.admin_left_menu)
        self.admin_mainBody = QtWidgets.QWidget(parent=self.admin_widget)
        self.admin_mainBody.setObjectName("admin_mainBody")
        self.admin_stackedWidget = QtWidgets.QStackedWidget(parent=self.admin_mainBody)
        self.admin_stackedWidget.setGeometry(QtCore.QRect(0, 0, 561, 591))
        self.admin_stackedWidget.setStyleSheet("")
        self.admin_stackedWidget.setObjectName("admin_stackedWidget")
        self.admin_home_page = QtWidgets.QWidget()
        self.admin_home_page.setObjectName("admin_home_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.admin_home_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.home_vertical_Layout = QtWidgets.QVBoxLayout()
        self.home_vertical_Layout.setObjectName("home_vertical_Layout")
        self.admin_home_frame = QtWidgets.QWidget(parent=self.admin_home_page)
        self.admin_home_frame.setObjectName("admin_home_frame")
        self.admin_header_frame = QtWidgets.QWidget(parent=self.admin_home_frame)
        self.admin_header_frame.setGeometry(QtCore.QRect(0, 0, 541, 79))
        self.admin_header_frame.setStyleSheet("#admin_header_frame{\n"
"    background-color:#476160;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.admin_header_frame.setObjectName("admin_header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.admin_header_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.admin_header_box = QtWidgets.QWidget(parent=self.admin_header_frame)
        self.admin_header_box.setObjectName("admin_header_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.admin_header_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.side_widget = QtWidgets.QWidget(parent=self.admin_header_box)
        self.side_widget.setObjectName("side_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.side_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.adm_menu_btn = QtWidgets.QPushButton(parent=self.side_widget)
        self.adm_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.adm_menu_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "sidemenu_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.adm_menu_btn.setIcon(icon3)
        self.adm_menu_btn.setIconSize(QtCore.QSize(25, 25))
        self.adm_menu_btn.setObjectName("adm_menu_btn")
        self.horizontalLayout_3.addWidget(self.adm_menu_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_2.addWidget(self.side_widget)
        self.admin_widget_2 = QtWidgets.QWidget(parent=self.admin_header_box)
        self.admin_widget_2.setObjectName("admin_widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.admin_widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.welcome_app_header = QtWidgets.QLabel(parent=self.admin_widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.welcome_app_header.setFont(font)
        self.welcome_app_header.setStyleSheet("#welcome_app_header{\n"
"color:white;\n"
"}")
        self.welcome_app_header.setObjectName("welcome_app_header")
        self.horizontalLayout_4.addWidget(self.welcome_app_header)
        self.horizontalLayout_2.addWidget(self.admin_widget_2)
        self.admin_widget_3 = QtWidgets.QWidget(parent=self.admin_header_box)
        self.admin_widget_3.setObjectName("admin_widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.admin_widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.admin_label_2 = QtWidgets.QLabel(parent=self.admin_widget_3)
        self.admin_label_2.setMaximumSize(QtCore.QSize(35, 30))
        self.admin_label_2.setText("")
        self.admin_label_2.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "admin_img.png")))
        self.admin_label_2.setScaledContents(True)
        self.admin_label_2.setObjectName("admin_label_2")
        self.horizontalLayout_6.addWidget(self.admin_label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_2.addWidget(self.admin_widget_3)
        self.horizontalLayout_7.addWidget(self.admin_header_box)
        self.admin_cards_widget = QtWidgets.QWidget(parent=self.admin_home_frame)
        self.admin_cards_widget.setGeometry(QtCore.QRect(0, 100, 541, 171))
        self.admin_cards_widget.setStyleSheet("")
        self.admin_cards_widget.setObjectName("admin_cards_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.admin_cards_widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.admin_card1 = QtWidgets.QFrame(parent=self.admin_cards_widget)
        self.admin_card1.setStyleSheet("#admin_card1{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.admin_card1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_card1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_card1.setObjectName("admin_card1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.admin_card1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.admin_frame = QtWidgets.QFrame(parent=self.admin_card1)
        self.admin_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame.setObjectName("admin_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.admin_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.user_increase_label = QtWidgets.QLabel(parent=self.admin_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.user_increase_label.setFont(font)
        self.user_increase_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.user_increase_label.setScaledContents(False)
        self.user_increase_label.setObjectName("user_increase_label")
        self.verticalLayout_7.addWidget(self.user_increase_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.increase_lable = QtWidgets.QLabel(parent=self.admin_frame)
        self.increase_lable.setMaximumSize(QtCore.QSize(40, 40))
        self.increase_lable.setText("")
        self.increase_lable.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "increase_icon.png")))
        self.increase_lable.setScaledContents(True)
        self.increase_lable.setObjectName("increase_lable")
        self.verticalLayout_7.addWidget(self.increase_lable, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.admin_frame)
        self.horizontalLayout_8.addWidget(self.admin_card1)
        self.admin_card2 = QtWidgets.QFrame(parent=self.admin_cards_widget)
        self.admin_card2.setStyleSheet("#admin_card2{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.admin_card2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_card2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_card2.setObjectName("admin_card2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.admin_card2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.admin_frame_2 = QtWidgets.QFrame(parent=self.admin_card2)
        self.admin_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame_2.setObjectName("admin_frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.admin_frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.active_user_label = QtWidgets.QLabel(parent=self.admin_frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.active_user_label.setFont(font)
        self.active_user_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.active_user_label.setObjectName("active_user_label")
        self.verticalLayout_8.addWidget(self.active_user_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.user_image_label = QtWidgets.QLabel(parent=self.admin_frame_2)
        self.user_image_label.setMaximumSize(QtCore.QSize(35, 35))
        self.user_image_label.setText("")
        self.user_image_label.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "active_users.png")))
        self.user_image_label.setScaledContents(True)
        self.user_image_label.setObjectName("user_image_label")
        self.verticalLayout_8.addWidget(self.user_image_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_4.addWidget(self.admin_frame_2)
        self.horizontalLayout_8.addWidget(self.admin_card2)
        self.admin_card3 = QtWidgets.QFrame(parent=self.admin_cards_widget)
        self.admin_card3.setStyleSheet("#admin_card3{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.admin_card3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_card3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_card3.setObjectName("admin_card3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.admin_card3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.admin_frame_3 = QtWidgets.QFrame(parent=self.admin_card3)
        self.admin_frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame_3.setObjectName("admin_frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.admin_frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.driver_to_assign_label = QtWidgets.QLabel(parent=self.admin_frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.driver_to_assign_label.setFont(font)
        self.driver_to_assign_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.driver_to_assign_label.setObjectName("driver_to_assign_label")
        self.verticalLayout_6.addWidget(self.driver_to_assign_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.assign_image_label = QtWidgets.QLabel(parent=self.admin_frame_3)
        self.assign_image_label.setMaximumSize(QtCore.QSize(35, 35))
        self.assign_image_label.setText("")
        self.assign_image_label.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "attend.png")))
        self.assign_image_label.setScaledContents(True)
        self.assign_image_label.setObjectName("assign_image_label")
        self.verticalLayout_6.addWidget(self.assign_image_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_5.addWidget(self.admin_frame_3)
        self.horizontalLayout_8.addWidget(self.admin_card3)
        self.admin_main_frame = QtWidgets.QWidget(parent=self.admin_home_frame)
        self.admin_main_frame.setGeometry(QtCore.QRect(0, 280, 559, 321))
        self.admin_main_frame.setObjectName("admin_main_frame")
        self.admin_banner_photo = QtWidgets.QLabel(parent=self.admin_main_frame)
        self.admin_banner_photo.setGeometry(QtCore.QRect(10, 0, 521, 281))
        self.admin_banner_photo.setStyleSheet("#admin_banner_photo{\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.admin_banner_photo.setText("")
        self.admin_banner_photo.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "admin_banner.png")))
        self.admin_banner_photo.setScaledContents(True)
        self.admin_banner_photo.setObjectName("admin_banner_photo")
        self.home_vertical_Layout.addWidget(self.admin_home_frame)
        self.verticalLayout_11.addLayout(self.home_vertical_Layout)
        self.admin_stackedWidget.addWidget(self.admin_home_page)
        self.view_users_page = QtWidgets.QWidget()
        self.view_users_page.setObjectName("view_users_page")
        self.view_users_form = QtWidgets.QFrame(parent=self.view_users_page)
        self.view_users_form.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.view_users_form.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.view_users_form.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.view_users_form.setObjectName("view_users_form")
        self.back_to_home = QtWidgets.QFrame(parent=self.view_users_form)
        self.back_to_home.setGeometry(QtCore.QRect(30, 490, 511, 61))
        self.back_to_home.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.back_to_home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.back_to_home.setObjectName("back_to_home")
        self.back_to_home_btn = QtWidgets.QPushButton(parent=self.back_to_home)
        self.back_to_home_btn.setGeometry(QtCore.QRect(140, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        self.back_to_home_btn.setFont(font)
        self.back_to_home_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_home_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.back_to_home_btn.setObjectName("back_to_home_btn")
        self.view_users_layout = QtWidgets.QFrame(parent=self.view_users_form)
        self.view_users_layout.setGeometry(QtCore.QRect(30, 10, 511, 481))
        self.view_users_layout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.view_users_layout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.view_users_layout.setObjectName("view_users_layout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.view_users_layout)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_users_label = QtWidgets.QLabel(parent=self.view_users_layout)
        self.view_users_label.setStyleSheet("QLabel {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 25px;            \n"
"}")
        self.view_users_label.setObjectName("view_users_label")
        self.gridLayout_2.addWidget(self.view_users_label, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.users_tab_widget = QtWidgets.QTabWidget(parent=self.view_users_layout)
        self.users_tab_widget.setStyleSheet("QTabBar::tab{\n"
"    color:white\n"
"\n"
"}\n"
"\n"
"QTabWidget {\n"
"    background-color: #879396;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.users_tab_widget.setObjectName("users_tab_widget")
        self.customers_tab = QtWidgets.QWidget()
        self.customers_tab.setObjectName("customers_tab")
        self.customer_table_widget = QtWidgets.QTableWidget(parent=self.customers_tab)
        self.customer_table_widget.setGeometry(QtCore.QRect(0, 0, 481, 361))
        self.customer_table_widget.setObjectName("customer_table_widget")
        self.customer_table_widget.setColumnCount(0)
        self.customer_table_widget.setRowCount(0)
        self.users_tab_widget.addTab(self.customers_tab, "")
        self.drivers_tab = QtWidgets.QWidget()
        self.drivers_tab.setObjectName("drivers_tab")
        self.driver_table_widget = QtWidgets.QTableWidget(parent=self.drivers_tab)
        self.driver_table_widget.setGeometry(QtCore.QRect(0, 0, 481, 361))
        self.driver_table_widget.setObjectName("driver_table_widget")
        self.driver_table_widget.setColumnCount(0)
        self.driver_table_widget.setRowCount(0)
        self.users_tab_widget.addTab(self.drivers_tab, "")
        self.gridLayout_2.addWidget(self.users_tab_widget, 1, 0, 1, 1)
        self.admin_stackedWidget.addWidget(self.view_users_page)
        self.assign_drivers_page = QtWidgets.QWidget()
        self.assign_drivers_page.setObjectName("assign_drivers_page")
        self.admin_assign_driverForm = QtWidgets.QFrame(parent=self.assign_drivers_page)
        self.admin_assign_driverForm.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.admin_assign_driverForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_assign_driverForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_assign_driverForm.setObjectName("admin_assign_driverForm")
        self.assign_btn_frame_6 = QtWidgets.QFrame(parent=self.admin_assign_driverForm)
        self.assign_btn_frame_6.setGeometry(QtCore.QRect(30, 490, 511, 61))
        self.assign_btn_frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.assign_btn_frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.assign_btn_frame_6.setObjectName("assign_btn_frame_6")
        self.confirm_assignment_btn = QtWidgets.QPushButton(parent=self.assign_btn_frame_6)
        self.confirm_assignment_btn.setGeometry(QtCore.QRect(270, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        self.confirm_assignment_btn.setFont(font)
        self.confirm_assignment_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirm_assignment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.confirm_assignment_btn.setObjectName("confirm_assignment_btn")
        self.cancel_assignment_btn = QtWidgets.QPushButton(parent=self.assign_btn_frame_6)
        self.cancel_assignment_btn.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        self.cancel_assignment_btn.setFont(font)
        self.cancel_assignment_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_assignment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.cancel_assignment_btn.setObjectName("cancel_assignment_btn")
        self.assign_driver_layout = QtWidgets.QFrame(parent=self.admin_assign_driverForm)
        self.assign_driver_layout.setGeometry(QtCore.QRect(30, 10, 511, 461))
        self.assign_driver_layout.setStyleSheet("")
        self.assign_driver_layout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.assign_driver_layout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.assign_driver_layout.setObjectName("assign_driver_layout")
        self.gridLayout = QtWidgets.QGridLayout(self.assign_driver_layout)
        self.gridLayout.setObjectName("gridLayout")
        self.assign_driver_label = QtWidgets.QLabel(parent=self.assign_driver_layout)
        self.assign_driver_label.setStyleSheet("QLabel {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 25px;            \n"
"}")
        self.assign_driver_label.setObjectName("assign_driver_label")
        self.gridLayout.addWidget(self.assign_driver_label, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.driver_tab_widget = QtWidgets.QTabWidget(parent=self.assign_driver_layout)
        self.driver_tab_widget.setStyleSheet("QTabBar::tab{\n"
"    color:white\n"
"\n"
"}\n"
"\n"
"QTabWidget {\n"
"    background-color: #879396;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.driver_tab_widget.setObjectName("driver_tab_widget")
        self.pending_tab = QtWidgets.QWidget()
        self.pending_tab.setObjectName("pending_tab")
        self.current_table_widget = QtWidgets.QTableWidget(parent=self.pending_tab)
        self.current_table_widget.setGeometry(QtCore.QRect(5, 11, 481, 341))
        self.current_table_widget.setObjectName("current_table_widget")
        self.current_table_widget.setColumnCount(0)
        self.current_table_widget.setRowCount(0)
        self.driver_tab_widget.addTab(self.pending_tab, "")
        self.completed_tab = QtWidgets.QWidget()
        self.completed_tab.setObjectName("completed_tab")
        self.pending_table_widget = QtWidgets.QTableWidget(parent=self.completed_tab)
        self.pending_table_widget.setGeometry(QtCore.QRect(0, 0, 481, 351))
        self.pending_table_widget.setObjectName("pending_table_widget")
        self.pending_table_widget.setColumnCount(0)
        self.pending_table_widget.setRowCount(0)
        self.driver_tab_widget.addTab(self.completed_tab, "")
        self.gridLayout.addWidget(self.driver_tab_widget, 1, 0, 1, 1)
        self.admin_stackedWidget.addWidget(self.assign_drivers_page)
        self.horizontalLayout.addWidget(self.admin_mainBody)

        self.retranslateUi(admin_dashboard)
        self.admin_stackedWidget.setCurrentIndex(2)
        self.users_tab_widget.setCurrentIndex(1)
        self.driver_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(admin_dashboard)

    def retranslateUi(self, admin_dashboard):
        _translate = QtCore.QCoreApplication.translate
        admin_dashboard.setWindowTitle(_translate("admin_dashboard", "Form"))
        self.admin_lable.setText(_translate("admin_dashboard", "Admin Menu"))
        self.admin_home_bn.setText(_translate("admin_dashboard", " Home"))
        self.assign_drivers_btn.setText(_translate("admin_dashboard", " Assign Drivers"))
        self.view_users_btn.setText(_translate("admin_dashboard", " View Users"))
        self.admin_logout_btn.setText(_translate("admin_dashboard", "Log Out"))
        self.welcome_app_header.setText(_translate("admin_dashboard", "Welcome Admin"))
        self.user_increase_label.setText(_translate("admin_dashboard", "User Increase"))
        self.active_user_label.setText(_translate("admin_dashboard", "5+ Active Users"))
        self.driver_to_assign_label.setText(_translate("admin_dashboard", "Drivers to Assign"))
        self.back_to_home_btn.setText(_translate("admin_dashboard", "Back to Home"))
        self.view_users_label.setText(_translate("admin_dashboard", "View All Users"))
        self.users_tab_widget.setTabText(self.users_tab_widget.indexOf(self.customers_tab), _translate("admin_dashboard", "Customers"))
        self.users_tab_widget.setTabText(self.users_tab_widget.indexOf(self.drivers_tab), _translate("admin_dashboard", "Drivers"))
        self.confirm_assignment_btn.setText(_translate("admin_dashboard", "Confirm"))
        self.cancel_assignment_btn.setText(_translate("admin_dashboard", "Cancel"))
        self.assign_driver_label.setText(_translate("admin_dashboard", "Assign Driver"))
        self.driver_tab_widget.setTabText(self.driver_tab_widget.indexOf(self.pending_tab), _translate("admin_dashboard", "Pending"))
        self.driver_tab_widget.setTabText(self.driver_tab_widget.indexOf(self.completed_tab), _translate("admin_dashboard", "Completed"))
