# Form implementation generated from reading ui file 'src/ui/Updated_Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from src.utils.constants import ICONS_DIR

class UiCustomerDashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(782, 603)
        Dashboard.setMinimumSize(QtCore.QSize(782, 603))
        Dashboard.setMaximumSize(QtCore.QSize(782, 603))
        Dashboard.setStyleSheet("#Dashboard{\n"
"    background-color: #8EA09F;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Dashboard)
        self.widget.setGeometry(QtCore.QRect(0, 0, 781, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none;\n"
"}\n"
"\n"
"#appHeader{\n"
"    color: #293737;\n"
"}\n"
"\n"
"#card1, #card2, #card3, #card4{\n"
"background-color: #fefeff;\n"
"border-radius: 20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(parent=self.widget)
        self.leftMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftMenu.setStyleSheet("#leftMenu{\n"
"    background-color: #293737;\n"
"}")
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sideMenu = QtWidgets.QFrame(parent=self.leftMenu)
        self.sideMenu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sideMenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sideMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sideMenu.setObjectName("sideMenu")
        self.layoutWidget = QtWidgets.QWidget(parent=self.sideMenu)
        self.layoutWidget.setGeometry(QtCore.QRect(-10, -10, 201, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(49, 20, 111, 24))
        self.label_8.setMaximumSize(QtCore.QSize(120, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.label_8.setObjectName("label_8")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 60, 201, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.home_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn.sizePolicy().hasHeightForWidth())
        self.home_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.home_btn.setFont(font)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "home.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_btn.setIcon(icon)
        self.home_btn.setIconSize(QtCore.QSize(32, 32))
        self.home_btn.setObjectName("homeButton")
        self.verticalLayout_10.addWidget(self.home_btn)
        self.ride_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ride_btn.sizePolicy().hasHeightForWidth())
        self.ride_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.ride_btn.setFont(font)
        self.ride_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ride_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "car.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ride_btn.setIcon(icon1)
        self.ride_btn.setIconSize(QtCore.QSize(35, 35))
        self.ride_btn.setObjectName("rideButton")
        self.verticalLayout_10.addWidget(self.ride_btn)
        self.driver_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driver_btn.sizePolicy().hasHeightForWidth())
        self.driver_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.driver_btn.setFont(font)
        self.driver_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.driver_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "driver.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.driver_btn.setIcon(icon2)
        self.driver_btn.setIconSize(QtCore.QSize(35, 35))
        self.driver_btn.setObjectName("driverButton")
        self.verticalLayout_10.addWidget(self.driver_btn)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 490, 161, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.log_out_btn = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.log_out_btn.setFont(font)
        self.log_out_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.log_out_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A;\n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #d17575;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.log_out_btn.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.log_out_btn)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.sideMenu)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.mainBody = QtWidgets.QWidget(parent=self.widget)
        self.mainBody.setObjectName("mainBody")
        self.customer_dash_panel = QtWidgets.QStackedWidget(parent=self.mainBody)
        self.customer_dash_panel.setGeometry(QtCore.QRect(0, 0, 600, 591))
        self.customer_dash_panel.setStyleSheet("")
        self.customer_dash_panel.setObjectName("customer_dash_panel")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardsFrame = QtWidgets.QWidget(parent=self.homePage)
        self.cardsFrame.setObjectName("cardsFrame")
        self.headerFrame = QtWidgets.QWidget(parent=self.cardsFrame)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 541, 66))
        self.headerFrame.setStyleSheet("#headerFrame{\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget1 = QtWidgets.QWidget(parent=self.headerFrame)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menu_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "sidemenu_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_btn.setIcon(icon3)
        self.menu_btn.setIconSize(QtCore.QSize(25, 25))
        self.menu_btn.setObjectName("menuButton")
        self.horizontalLayout_3.addWidget(self.menu_btn)
        self.appHeader = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.appHeader.setFont(font)
        self.appHeader.setStyleSheet("#appHeader{\n"
"color:white;\n"
"}")
        self.appHeader.setObjectName("appHeader")
        self.horizontalLayout_3.addWidget(self.appHeader)
        self.horizontalLayout_2.addWidget(self.widget1, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_2 = QtWidgets.QWidget(parent=self.headerFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchFrame = QtWidgets.QFrame(parent=self.widget_2)
        self.searchFrame.setMinimumSize(QtCore.QSize(215, 0))
        self.searchFrame.setStyleSheet("#searchFrame{\n"
"    background-color: transparent;;\n"
"    border-radius: 20px;\n"
"    border: 2px solid #293737;\n"
"}")
        self.searchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.searchFrame)
        self.label_2.setMinimumSize(QtCore.QSize(24, 24))
        self.label_2.setMaximumSize(QtCore.QSize(24, 24))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "search.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.searchBar = QtWidgets.QLineEdit(parent=self.searchFrame)
        self.searchBar.setStyleSheet("#searchBar{\n"
"background: transparent;\n"
"}")
        self.searchBar.setObjectName("searchBar")
        self.horizontalLayout_5.addWidget(self.searchBar)
        self.horizontalLayout_4.addWidget(self.searchFrame)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_3 = QtWidgets.QWidget(parent=self.headerFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.account_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.account_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.account_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "user_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.account_btn.setIcon(icon4)
        self.account_btn.setIconSize(QtCore.QSize(25, 25))
        self.account_btn.setObjectName("accounButton")
        self.horizontalLayout_6.addWidget(self.account_btn)
        self.horizontalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.widget2 = QtWidgets.QWidget(parent=self.cardsFrame)
        self.widget2.setGeometry(QtCore.QRect(0, 100, 541, 171))
        self.widget2.setStyleSheet("")
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.card1 = QtWidgets.QFrame(parent=self.widget2)
        self.card1.setStyleSheet("#card1{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"}")
        self.card1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card1.setObjectName("card1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.card1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.card1)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "fare_icon.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_8.addWidget(self.card1)
        self.card2 = QtWidgets.QFrame(parent=self.widget2)
        self.card2.setStyleSheet("#card2{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"}")
        self.card2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card2.setObjectName("card2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.card2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.card2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "stars.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.horizontalLayout_8.addWidget(self.card2)
        self.card3 = QtWidgets.QFrame(parent=self.widget2)
        self.card3.setStyleSheet("#card3{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"}")
        self.card3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card3.setObjectName("card3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.card3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(parent=self.card3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "available.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.horizontalLayout_8.addWidget(self.card3)
        self.mainFrame = QtWidgets.QWidget(parent=self.cardsFrame)
        self.mainFrame.setGeometry(QtCore.QRect(0, 280, 559, 321))
        self.mainFrame.setObjectName("mainFrame")
        self.bannerPhoto = QtWidgets.QLabel(parent=self.mainFrame)
        self.bannerPhoto.setGeometry(QtCore.QRect(10, 0, 521, 281))
        self.bannerPhoto.setStyleSheet("#bannerPhoto{\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.bannerPhoto.setText("")
        self.bannerPhoto.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "banner_img.png")))
        self.bannerPhoto.setScaledContents(True)
        self.bannerPhoto.setObjectName("bannerPhoto")
        self.verticalLayout.addWidget(self.cardsFrame)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.customer_dash_panel.addWidget(self.homePage)
        self.book_ride_page = QtWidgets.QWidget()
        self.book_ride_page.setObjectName("bookRidepage")
        self.customer_dash_panel.addWidget(self.book_ride_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profilePage")
        self.edit_profile_form = QtWidgets.QFrame(parent=self.profile_page)
        self.edit_profile_form.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.edit_profile_form.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.edit_profile_form.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.edit_profile_form.setObjectName("driverForm_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.edit_profile_form)
        self.frame_7.setGeometry(QtCore.QRect(30, 490, 511, 61))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.update_account_btn = QtWidgets.QPushButton(parent=self.frame_7)
        self.update_account_btn.setGeometry(QtCore.QRect(270, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.update_account_btn.setFont(font)
        self.update_account_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.update_account_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.update_account_btn.setObjectName("confirmEdit_btn")
        self.cancel_edit_btn = QtWidgets.QPushButton(parent=self.frame_7)
        self.cancel_edit_btn.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.cancel_edit_btn.setFont(font)
        self.cancel_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_edit_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.cancel_edit_btn.setObjectName("cancelEdit_btn")
        self.frame_8 = QtWidgets.QFrame(parent=self.edit_profile_form)
        self.frame_8.setGeometry(QtCore.QRect(30, 10, 511, 391))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 1, 1, 1)
        self.lastname = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastname.sizePolicy().hasHeightForWidth())
        self.lastname.setSizePolicy(sizePolicy)
        self.lastname.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.lastname.setObjectName("lastname")
        self.gridLayout_2.addWidget(self.lastname, 2, 1, 1, 1)
        self.phonenum = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenum.sizePolicy().hasHeightForWidth())
        self.phonenum.setSizePolicy(sizePolicy)
        self.phonenum.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.phonenum.setObjectName("phonenum")
        self.gridLayout_2.addWidget(self.phonenum, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.new_password = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password.sizePolicy().hasHeightForWidth())
        self.new_password.setSizePolicy(sizePolicy)
        self.new_password.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.new_password.setObjectName("new_password")
        self.gridLayout_2.addWidget(self.new_password, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_22.setStyleSheet("QLabel {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 25px;            \n"
"}")
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 1, 1, 1)
        self.email = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email.sizePolicy().hasHeightForWidth())
        self.email.setSizePolicy(sizePolicy)
        self.email.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.email.setObjectName("email")
        self.gridLayout_2.addWidget(self.email, 4, 1, 1, 1)
        self.firstname = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstname.sizePolicy().hasHeightForWidth())
        self.firstname.setSizePolicy(sizePolicy)
        self.firstname.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"/* Style for when the mouse hovers over the button */\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.firstname.setObjectName("firstname")
        self.gridLayout_2.addWidget(self.firstname, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 1, 1, 1)
        self.confirm_password = InputEdit(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_password.sizePolicy().hasHeightForWidth())
        self.confirm_password.setSizePolicy(sizePolicy)
        self.confirm_password.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")

        self.confirm_password.setObjectName("confirm_password")
        self.gridLayout_2.addWidget(self.confirm_password, 6, 1, 1, 1)
        self.authorize_info_update = QtWidgets.QCheckBox(parent=self.edit_profile_form)
        self.authorize_info_update.setGeometry(QtCore.QRect(40, 430, 493, 18))
        font = QtGui.QFont()
        self.authorize_info_update.setFont(font)
        self.authorize_info_update.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.authorize_info_update.setStyleSheet("QCheckBox{\n"
"    color: white;                \n"
"    font-size: 15px;             \n"
"}\n"
"")
        self.authorize_info_update.setObjectName("authorize_Info_update")
        self.customer_dash_panel.addWidget(self.profile_page)
        self.become_driver_page = QtWidgets.QWidget()
        self.become_driver_page.setObjectName("becomeDriverPage")
        self.driver_form = QtWidgets.QFrame(parent=self.become_driver_page)
        self.driver_form.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.driver_form.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_form.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_form.setObjectName("driverForm")
        self.frame_6 = QtWidgets.QFrame(parent=self.driver_form)
        self.frame_6.setGeometry(QtCore.QRect(30, 490, 511, 61))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.confirm_driver_reg_btn = QtWidgets.QPushButton(parent=self.frame_6)
        self.confirm_driver_reg_btn.setGeometry(QtCore.QRect(270, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.confirm_driver_reg_btn.setFont(font)
        self.confirm_driver_reg_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirm_driver_reg_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.confirm_driver_reg_btn.setObjectName("confirmDriver_btn")
        self.cancel_driver_reg_btn = QtWidgets.QPushButton(parent=self.frame_6)
        self.cancel_driver_reg_btn.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.cancel_driver_reg_btn.setFont(font)
        self.cancel_driver_reg_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_driver_reg_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.cancel_driver_reg_btn.setObjectName("cancleDriver_btn")
        self.driver_reg_layout = QtWidgets.QFrame(parent=self.driver_form)
        self.driver_reg_layout.setGeometry(QtCore.QRect(30, 10, 511, 391))
        self.driver_reg_layout.setStyleSheet("")
        self.driver_reg_layout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_reg_layout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_reg_layout.setObjectName("driver_reg_layout")
        self.gridLayout = QtWidgets.QGridLayout(self.driver_reg_layout)
        self.gridLayout.setObjectName("gridLayout")
        self.yes_no_dropbox = QtWidgets.QComboBox(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yes_no_dropbox.sizePolicy().hasHeightForWidth())
        self.yes_no_dropbox.setSizePolicy(sizePolicy)
        self.yes_no_dropbox.setStyleSheet("QComboBox {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #466061;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}\n"
"\n"
"")
        self.yes_no_dropbox.setObjectName("yes_No")
        self.yes_no_dropbox.addItem("")
        self.yes_no_dropbox.addItem("")
        self.gridLayout.addWidget(self.yes_no_dropbox, 6, 1, 1, 1)
        self.car_colour = QtWidgets.QLineEdit(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_colour.sizePolicy().hasHeightForWidth())
        self.car_colour.setSizePolicy(sizePolicy)
        self.car_colour.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.car_colour.setText("")
        self.car_colour.setObjectName("carColour")
        self.gridLayout.addWidget(self.car_colour, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 1, 1, 1)
        self.manufacture_year = QtWidgets.QLineEdit(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manufacture_year.sizePolicy().hasHeightForWidth())
        self.manufacture_year.setSizePolicy(sizePolicy)
        self.manufacture_year.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.manufacture_year.setText("")
        self.manufacture_year.setObjectName("manu_Year")
        self.gridLayout.addWidget(self.manufacture_year, 4, 0, 1, 1)
        self.license_plate_reg = QtWidgets.QLineEdit(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.license_plate_reg.sizePolicy().hasHeightForWidth())
        self.license_plate_reg.setSizePolicy(sizePolicy)
        self.license_plate_reg.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.license_plate_reg.setText("")
        self.license_plate_reg.setObjectName("licensePlate_reg")
        self.gridLayout.addWidget(self.license_plate_reg, 6, 0, 1, 1)
        self.car_model = QtWidgets.QLineEdit(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_model.sizePolicy().hasHeightForWidth())
        self.car_model.setSizePolicy(sizePolicy)
        self.car_model.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.car_model.setText("")
        self.car_model.setObjectName("carMode")
        self.gridLayout.addWidget(self.car_model, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")

        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 1, 1, 1)
        self.car_make = QtWidgets.QLineEdit(parent=self.driver_reg_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_make.sizePolicy().hasHeightForWidth())
        self.car_make.setSizePolicy(sizePolicy)
        self.car_make.setStyleSheet("QLineEdit {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 15px;            \n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: #4A5C66; /* Slightly lighter background on hover */\n"
"    border: 2px solid #FFFFFF; /* Highlight the border on hover */\n"
"}")
        self.car_make.setObjectName("carMake")
        self.gridLayout.addWidget(self.car_make, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: white;                \n"
"    font-size: 18px;             \n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.driver_reg_layout)
        self.label_15.setStyleSheet("QLabel {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 25px;            \n"
"}")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.confirm_driver_checkbox = QtWidgets.QCheckBox(parent=self.driver_form)
        self.confirm_driver_checkbox.setGeometry(QtCore.QRect(40, 430, 493, 18))
        font = QtGui.QFont()

        self.confirm_driver_checkbox.setFont(font)
        self.confirm_driver_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirm_driver_checkbox.setStyleSheet("QCheckBox{\n"
"    color: white;                \n"
"    font-size: 15px;             \n"
"}\n"
"")
        self.confirm_driver_checkbox.setObjectName("confirmCheckbox_driver")
        self.customer_dash_panel.addWidget(self.become_driver_page)
        self.horizontalLayout.addWidget(self.mainBody)

        self.retranslateUi(Dashboard)
        self.customer_dash_panel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Form"))
        self.label_8.setText(_translate("Dashboard", "Main Menu"))
        self.home_btn.setText(_translate("Dashboard", " Home"))
        self.ride_btn.setText(_translate("Dashboard", " Book a Ride"))
        self.driver_btn.setText(_translate("Dashboard", " Drive for Us"))
        self.log_out_btn.setText(_translate("Dashboard", "Log Out"))
        self.appHeader.setText(_translate("Dashboard", "A & C Taxi Services"))
        self.searchBar.setPlaceholderText(_translate("Dashboard", "Search Something"))
        self.label.setText(_translate("Dashboard", "Cheapest Fares"))
        self.label_3.setText(_translate("Dashboard", "5 Star Rated"))
        self.label_7.setText(_translate("Dashboard", "Always Available"))
        self.update_account_btn.setText(_translate("Dashboard", "Confirm"))
        self.cancel_edit_btn.setText(_translate("Dashboard", "Cancel"))
        self.label_21.setText(_translate("Dashboard", "Updated Last Name"))
        self.label_20.setText(_translate("Dashboard", "Updated Phone Number"))
        self.label_16.setText(_translate("Dashboard", "Updated First Name"))
        self.label_22.setText(_translate("Dashboard", "Edit Your Profile Information"))
        self.label_18.setText(_translate("Dashboard", "Re-enter New Password"))
        self.label_17.setText(_translate("Dashboard", "New Password"))
        self.label_19.setText(_translate("Dashboard", "Updated Email Address"))
        self.authorize_info_update.setText(_translate("Dashboard", "I authorize my information to be updated"))
        self.confirm_driver_reg_btn.setText(_translate("Dashboard", "Confirm"))
        self.cancel_driver_reg_btn.setText(_translate("Dashboard", "Cancel"))
        self.yes_no_dropbox.setItemText(0, _translate("Dashboard", "No"))
        self.yes_no_dropbox.setItemText(1, _translate("Dashboard", "Yes"))
        self.label_9.setText(_translate("Dashboard", "Make of Vehicle"))
        self.label_14.setText(_translate("Dashboard", "License Plate Registration"))
        self.label_13.setText(_translate("Dashboard", "Have you been a driver before?"))
        self.label_12.setText(_translate("Dashboard", "Colour of Vehicle"))
        self.label_11.setText(_translate("Dashboard", "Manufacture Year"))
        self.label_10.setText(_translate("Dashboard", "Model  of Vehicle"))
        self.label_15.setText(_translate("Dashboard", "Driver Registration"))
        self.confirm_driver_checkbox.setText(_translate("Dashboard", "Confirm Driver Registration"))
from src.widgets import InputEdit