# Form implementation generated from reading ui file 'src/ui/driver_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from src.utils.constants import ICONS_DIR

class UiDriverDashboard(object):
    def setupUi(self, driver_dashboard):
        driver_dashboard.setObjectName("driver_dashboard")
        driver_dashboard.resize(782, 603)
        driver_dashboard.setMinimumSize(QtCore.QSize(782, 603))
        driver_dashboard.setMaximumSize(QtCore.QSize(782, 603))
        driver_dashboard.setStyleSheet("#driver_dashboard{\n"
"    background-color: #8EA09F;\n"
"}")
        self.driver_widget = QtWidgets.QWidget(parent=driver_dashboard)
        self.driver_widget.setGeometry(QtCore.QRect(0, 0, 781, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driver_widget.sizePolicy().hasHeightForWidth())
        self.driver_widget.setSizePolicy(sizePolicy)
        self.driver_widget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none;\n"
"}\n"
"\n"
"#appHeader{\n"
"    color: #293737;\n"
"}\n"
"\n"
"#card1, #card2, #card3, #card4{\n"
"background-color: #fefeff;\n"
"border-radius: 20px;\n"
"}")
        self.driver_widget.setObjectName("driver_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.driver_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.driver_left_menu = QtWidgets.QWidget(parent=self.driver_widget)
        self.driver_left_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.driver_left_menu.setStyleSheet("#driver_left_menu{\n"
"    background-color: #293737;\n"
"}")
        self.driver_left_menu.setObjectName("driver_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.driver_left_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.driver_side_menu = QtWidgets.QFrame(parent=self.driver_left_menu)
        self.driver_side_menu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.driver_side_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_side_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_side_menu.setObjectName("driver_side_menu")
        self.layoutWidget = QtWidgets.QWidget(parent=self.driver_side_menu)
        self.layoutWidget.setGeometry(QtCore.QRect(-10, -10, 201, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.driver_vertical_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.driver_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.driver_vertical_layout.setObjectName("driver_vertical_layout")
        self.driver_frame_4 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.driver_frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.driver_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_frame_4.setObjectName("driver_frame_4")
        self.driver_lable = QtWidgets.QLabel(parent=self.driver_frame_4)
        self.driver_lable.setGeometry(QtCore.QRect(40, 20, 125, 24))
        self.driver_lable.setMaximumSize(QtCore.QSize(125, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.driver_lable.setFont(font)
        self.driver_lable.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.driver_lable.setObjectName("driver_lable")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.driver_frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 60, 201, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.driver_vertical_layout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.driver_vertical_layout_2.setContentsMargins(0, 0, 0, 0)
        self.driver_vertical_layout_2.setSpacing(10)
        self.driver_vertical_layout_2.setObjectName("driver_vertical_layout_2")
        self.home_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn.sizePolicy().hasHeightForWidth())
        self.home_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.home_btn.setFont(font)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "home.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_btn.setIcon(icon)
        self.home_btn.setIconSize(QtCore.QSize(32, 32))
        self.home_btn.setObjectName("home_btn")
        self.driver_vertical_layout_2.addWidget(self.home_btn)
        self.assigned_trips_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assigned_trips_btn.sizePolicy().hasHeightForWidth())
        self.assigned_trips_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.assigned_trips_btn.setFont(font)
        self.assigned_trips_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assigned_trips_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;      \n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A; \n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "route_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.assigned_trips_btn.setIcon(icon1)
        self.assigned_trips_btn.setIconSize(QtCore.QSize(40, 40))
        self.assigned_trips_btn.setObjectName("assigned_trips_btn")
        self.driver_vertical_layout_2.addWidget(self.assigned_trips_btn)
        self.driver_frame_5 = QtWidgets.QFrame(parent=self.driver_frame_4)
        self.driver_frame_5.setGeometry(QtCore.QRect(20, 490, 161, 81))
        self.driver_frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_frame_5.setObjectName("driver_frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.driver_frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.logout_btn = QtWidgets.QPushButton(parent=self.driver_frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.logout_btn.setFont(font)
        self.logout_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logout_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 14px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #556D7A;\n"
"    border-radius: 8px;\n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for when the mouse hovers over the button */\n"
"QPushButton:hover {\n"
"    background-color: #d17575;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_12.addWidget(self.logout_btn)
        self.driver_vertical_layout.addWidget(self.driver_frame_4)
        self.verticalLayout_2.addWidget(self.driver_side_menu)
        self.horizontalLayout.addWidget(self.driver_left_menu)
        self.driver_mainBody = QtWidgets.QWidget(parent=self.driver_widget)
        self.driver_mainBody.setObjectName("driver_mainBody")
        self.driver_stackedWidget = QtWidgets.QStackedWidget(parent=self.driver_mainBody)
        self.driver_stackedWidget.setGeometry(QtCore.QRect(0, 0, 561, 591))
        self.driver_stackedWidget.setStyleSheet("")
        self.driver_stackedWidget.setObjectName("driver_stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.driver_home_vertical_Layout = QtWidgets.QVBoxLayout()
        self.driver_home_vertical_Layout.setObjectName("driver_home_vertical_Layout")
        self.driver_home_frame = QtWidgets.QWidget(parent=self.home_page)
        self.driver_home_frame.setObjectName("driver_home_frame")
        self.driver_header_frame = QtWidgets.QWidget(parent=self.driver_home_frame)
        self.driver_header_frame.setGeometry(QtCore.QRect(0, 0, 541, 71))
        self.driver_header_frame.setStyleSheet("#driver_header_frame{\n"
"    background-color:#476160;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.driver_header_frame.setObjectName("driver_header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.driver_header_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.driver_header_box = QtWidgets.QWidget(parent=self.driver_header_frame)
        self.driver_header_box.setObjectName("driver_header_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.driver_header_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.driver_side_widget = QtWidgets.QWidget(parent=self.driver_header_box)
        self.driver_side_widget.setObjectName("driver_side_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.driver_side_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.driver_menu_btn = QtWidgets.QPushButton(parent=self.driver_side_widget)
        self.driver_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.driver_menu_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "sidemenu_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.driver_menu_btn.setIcon(icon2)
        self.driver_menu_btn.setIconSize(QtCore.QSize(25, 25))
        self.driver_menu_btn.setObjectName("driver_menu_btn")
        self.horizontalLayout_3.addWidget(self.driver_menu_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_2.addWidget(self.driver_side_widget)
        self.driver_widget_2 = QtWidgets.QWidget(parent=self.driver_header_box)
        self.driver_widget_2.setObjectName("driver_widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.driver_widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.driver_welcome_app_header = QtWidgets.QLabel(parent=self.driver_widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.driver_welcome_app_header.setFont(font)
        self.driver_welcome_app_header.setStyleSheet("#driver_welcome_app_header{\n"
"color:white;\n"
"}")
        self.driver_welcome_app_header.setObjectName("driver_welcome_app_header")
        self.horizontalLayout_4.addWidget(self.driver_welcome_app_header)
        self.horizontalLayout_2.addWidget(self.driver_widget_2)
        self.driver_widget_3 = QtWidgets.QWidget(parent=self.driver_header_box)
        self.driver_widget_3.setObjectName("driver_widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.driver_widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.driver_account_btn = QtWidgets.QPushButton(parent=self.driver_widget_3)
        self.driver_account_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(str(ICONS_DIR / "user_icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.driver_account_btn.setIcon(icon3)
        self.driver_account_btn.setIconSize(QtCore.QSize(25, 25))
        self.driver_account_btn.setObjectName("driver_account_btn")
        self.horizontalLayout_6.addWidget(self.driver_account_btn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_2.addWidget(self.driver_widget_3)
        self.horizontalLayout_7.addWidget(self.driver_header_box)
        self.driver_cards_widget = QtWidgets.QWidget(parent=self.driver_home_frame)
        self.driver_cards_widget.setGeometry(QtCore.QRect(0, 90, 541, 171))
        self.driver_cards_widget.setStyleSheet("")
        self.driver_cards_widget.setObjectName("driver_cards_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.driver_cards_widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.driver_card1 = QtWidgets.QFrame(parent=self.driver_cards_widget)
        self.driver_card1.setStyleSheet("#driver_card1{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.driver_card1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_card1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_card1.setObjectName("driver_card1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.driver_card1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.driver_frame = QtWidgets.QFrame(parent=self.driver_card1)
        self.driver_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_frame.setObjectName("driver_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.driver_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.professional_label = QtWidgets.QLabel(parent=self.driver_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.professional_label.setFont(font)
        self.professional_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.professional_label.setScaledContents(False)
        self.professional_label.setObjectName("professional_label")
        self.verticalLayout_7.addWidget(self.professional_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.professional_icon_lable = QtWidgets.QLabel(parent=self.driver_frame)
        self.professional_icon_lable.setMaximumSize(QtCore.QSize(40, 40))
        self.professional_icon_lable.setText("")
        self.professional_icon_lable.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "professional.png")))
        self.professional_icon_lable.setScaledContents(True)
        self.professional_icon_lable.setObjectName("professional_icon_lable")
        self.verticalLayout_7.addWidget(self.professional_icon_lable, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.driver_frame)
        self.horizontalLayout_8.addWidget(self.driver_card1)
        self.driver_card2 = QtWidgets.QFrame(parent=self.driver_cards_widget)
        self.driver_card2.setStyleSheet("#driver_card2{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.driver_card2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_card2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_card2.setObjectName("driver_card2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.driver_card2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.driver_frame_2 = QtWidgets.QFrame(parent=self.driver_card2)
        self.driver_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_frame_2.setObjectName("driver_frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.driver_frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.be_careful_label = QtWidgets.QLabel(parent=self.driver_frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.be_careful_label.setFont(font)
        self.be_careful_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.be_careful_label.setObjectName("be_careful_label")
        self.verticalLayout_8.addWidget(self.be_careful_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.careful_icon_label = QtWidgets.QLabel(parent=self.driver_frame_2)
        self.careful_icon_label.setMaximumSize(QtCore.QSize(35, 35))
        self.careful_icon_label.setText("")
        self.careful_icon_label.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "safe.png")))
        self.careful_icon_label.setScaledContents(True)
        self.careful_icon_label.setObjectName("careful_icon_label")
        self.verticalLayout_8.addWidget(self.careful_icon_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_4.addWidget(self.driver_frame_2)
        self.horizontalLayout_8.addWidget(self.driver_card2)
        self.driver_card3 = QtWidgets.QFrame(parent=self.driver_cards_widget)
        self.driver_card3.setStyleSheet("#driver_card3{\n"
"    background-color: #466061;\n"
"    border: 5px solid #293737;\n"
"    border-radius: 20px;\n"
"}")
        self.driver_card3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_card3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_card3.setObjectName("driver_card3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.driver_card3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.driver_frame_3 = QtWidgets.QFrame(parent=self.driver_card3)
        self.driver_frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.driver_frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.driver_frame_3.setObjectName("driver_frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.driver_frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.be_on_time_label = QtWidgets.QLabel(parent=self.driver_frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.be_on_time_label.setFont(font)
        self.be_on_time_label.setStyleSheet("  QLabel {\n"
"        color: white;\n"
"    }")
        self.be_on_time_label.setObjectName("be_on_time_label")
        self.verticalLayout_6.addWidget(self.be_on_time_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.time_image_label = QtWidgets.QLabel(parent=self.driver_frame_3)
        self.time_image_label.setMaximumSize(QtCore.QSize(35, 35))
        self.time_image_label.setText("")
        self.time_image_label.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "on_time.png")))
        self.time_image_label.setScaledContents(True)
        self.time_image_label.setObjectName("time_image_label")
        self.verticalLayout_6.addWidget(self.time_image_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_5.addWidget(self.driver_frame_3)
        self.horizontalLayout_8.addWidget(self.driver_card3)
        self.driver_main_frame = QtWidgets.QWidget(parent=self.driver_home_frame)
        self.driver_main_frame.setGeometry(QtCore.QRect(0, 280, 559, 321))
        self.driver_main_frame.setObjectName("driver_main_frame")
        self.driver_banner_photo = QtWidgets.QLabel(parent=self.driver_main_frame)
        self.driver_banner_photo.setGeometry(QtCore.QRect(10, 0, 521, 281))
        self.driver_banner_photo.setStyleSheet("#driver_banner_photo{\n"
"    border: 5px solid #293737;\n"
"    border-radius: 8px;  \n"
"}")
        self.driver_banner_photo.setText("")
        self.driver_banner_photo.setPixmap(QtGui.QPixmap(str(ICONS_DIR / "driver_banner.png")))
        self.driver_banner_photo.setScaledContents(True)
        self.driver_banner_photo.setObjectName("driver_banner_photo")
        self.driver_home_vertical_Layout.addWidget(self.driver_home_frame)
        self.verticalLayout_11.addLayout(self.driver_home_vertical_Layout)
        self.driver_stackedWidget.addWidget(self.home_page)
        self.view_trip_page = QtWidgets.QWidget()
        self.view_trip_page.setObjectName("view_trip_page")
        self.view_trips_form = QtWidgets.QFrame(parent=self.view_trip_page)
        self.view_trips_form.setGeometry(QtCore.QRect(-10, 0, 561, 581))
        self.view_trips_form.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.view_trips_form.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.view_trips_form.setObjectName("view_trips_form")
        self.view_trips_layout = QtWidgets.QFrame(parent=self.view_trips_form)
        self.view_trips_layout.setGeometry(QtCore.QRect(30, 0, 511, 581))
        self.view_trips_layout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.view_trips_layout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.view_trips_layout.setObjectName("view_trips_layout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.view_trips_layout)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_trips_label = QtWidgets.QLabel(parent=self.view_trips_layout)
        self.view_trips_label.setStyleSheet("QLabel {\n"
"    background-color: #466061; \n"
"    border: 2px solid #101717; \n"
"    border-radius: 8px; \n"
"    padding: 6px;\n"
"    color: white; \n"
"    font-size: 25px;            \n"
"}")
        self.view_trips_label.setObjectName("view_trips_label")
        self.gridLayout_2.addWidget(self.view_trips_label, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.view_trips_layout)
        self.tabWidget.setStyleSheet("QTabBar::tab{\n"
"    color:white\n"
"\n"
"}\n"
"\n"
"QTabWidget {\n"
"    background-color: #8ea19f;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.assigned_drives_tab = QtWidgets.QWidget()
        self.assigned_drives_tab.setObjectName("assigned_drives_tab")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.assigned_drives_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(-4, 0, 491, 471))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.tab_verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.tab_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.tab_verticalLayout.setObjectName("tab_verticalLayout")
        self.active_booking_table = QtWidgets.QTableWidget(parent=self.layoutWidget2)
        self.active_booking_table.setObjectName("active_booking_table")
        self.active_booking_table.setColumnCount(0)
        self.active_booking_table.setRowCount(0)
        #STYLE SHEET FOR ASSIGNED DRIVE TABLE
        self.active_booking_table.setStyleSheet(
            "QTableWidget {\n"
            "    background-color: #7d918f;\n"
            "    color:white;\n"
            "    font-size: 14px;\n"
            "    gridline-color:#293736;\n"
            "    border:1px solid #293736;\n"
            "}"
            "QHeaderView::section {\n"
            "    background-color: #476061;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 14px;\n"
            "    border:1px solid #293736;\n"
            "}")

        self.tab_verticalLayout.addWidget(self.active_booking_table)
        self.back_to_home = QtWidgets.QFrame(parent=self.layoutWidget2)
        self.back_to_home.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.back_to_home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.back_to_home.setObjectName("back_to_home")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.back_to_home)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.go_to_home_btn = QtWidgets.QPushButton(parent=self.back_to_home)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        self.go_to_home_btn.setFont(font)
        self.go_to_home_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.go_to_home_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.go_to_home_btn.setObjectName("go_to_home_btn")
        self.horizontalLayout_5.addWidget(self.go_to_home_btn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)


        self.tab_verticalLayout.addWidget(self.back_to_home)
        self.tabWidget.addTab(self.assigned_drives_tab, "")
        self.completed_drives_tab = QtWidgets.QWidget()
        self.completed_drives_tab.setObjectName("completed_drives_tab")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.completed_drives_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(-3, 0, 491, 461))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.completed_verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.completed_verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.completed_verticalLayout_9.setObjectName("completed_verticalLayout_9")
        self.completed_booking_table = QtWidgets.QTableWidget(parent=self.layoutWidget3)
        self.completed_booking_table.setObjectName("completed_booking_table")
        self.completed_booking_table.setColumnCount(0)
        self.completed_booking_table.setRowCount(0)
        #STYLE SHEET FOR COMPLETED DRIVES TABLE
        self.completed_booking_table.setStyleSheet(
            "QTableWidget {\n"
            "    background-color: #7d918f;\n"
            "    color:white;\n"
            "    font-size: 14px;\n"
            "    gridline-color:#293736;\n"
            "    border:1px solid #293736;\n"
            "}"
            "QHeaderView::section {\n"
            "    background-color: #476061;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 14px;\n"
            "    border:1px solid #293736;\n"
            "}")
        self.completed_verticalLayout_9.addWidget(self.completed_booking_table)
        self.back_to_home_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.back_to_home_btn.setStyleSheet("QPushButton {\n"
"    background-color: #476061;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    padding: 10px 10px;\n"
"\n"
"    /* Border and Shape */\n"
"    border: 2px solid #101717; \n"
"    border-radius: 15px; \n"
"    margin: 5px 10px 5px 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Style for hover over button */\n"
"QPushButton:pressed {\n"
"    background-color: #4A5C66;\n"
"    border: 2px solid #FFFFFF;\n"
"}")
        self.back_to_home_btn.setObjectName("back_to_home_btn")
        self.completed_verticalLayout_9.addWidget(self.back_to_home_btn)
        self.tabWidget.addTab(self.completed_drives_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.driver_stackedWidget.addWidget(self.view_trip_page)
        self.horizontalLayout.addWidget(self.driver_mainBody)

        self.retranslateUi(driver_dashboard)
        self.driver_stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(driver_dashboard)

    def retranslateUi(self, driver_dashboard):
        _translate = QtCore.QCoreApplication.translate
        driver_dashboard.setWindowTitle(_translate("driver_dashboard", "Form"))
        self.driver_lable.setText(_translate("driver_dashboard", "Driver Menu"))
        self.home_btn.setText(_translate("driver_dashboard", " Home"))
        self.assigned_trips_btn.setText(_translate("driver_dashboard", "Assigned Trips"))
        self.logout_btn.setText(_translate("driver_dashboard", "Log Out"))
        self.driver_welcome_app_header.setText(_translate("driver_dashboard", "Welcome Driver"))
        self.professional_label.setText(_translate("driver_dashboard", "Be Professional"))
        self.be_careful_label.setText(_translate("driver_dashboard", "Be Careful"))
        self.be_on_time_label.setText(_translate("driver_dashboard", "Be On Time"))
        self.view_trips_label.setText(_translate("driver_dashboard", "View Assigned Trips"))
        self.go_to_home_btn.setText(_translate("driver_dashboard", "Back to Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assigned_drives_tab), _translate("driver_dashboard", "Assigned Drive"))
        self.back_to_home_btn.setText(_translate("driver_dashboard", "Back to Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.completed_drives_tab), _translate("driver_dashboard", "Completed Drives"))
